# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='additional_tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='add_notes', to='app.Tag'),
        ),
    ]
